module.exports = [
  "Fiction",
  "Non-fiction",
  "Fantasy",
  "Sci-Fi",
  "Mystery/Thriller",
  "Romance",
  "Historical",
  "Classics",
  "Poetry",
  "Biography/Memoir",
  "Horror",
  "Young Adult",
  "Contemporary",
  "Literary Fiction",
  "Dystopian",
  "Magical Realism",
  "Graphic Novels",
  "Self-Help",
  "Philosophy",
  "Short Stories",
  "Mythology",
];
